#!/usr/bin/env bash

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/../../"
. ${BASE_DIR}.env

echo "== building image with alpine '$ALPINE_VERSION' and terraform '$TERRAFORM_VERSION'"

docker build \
  --build-arg ALPINE_VERSION=$ALPINE_VERSION --build-arg TERRAFORM_VERSION=$TERRAFORM_VERSION \
  -f Dockerfile -t $IMAGE_NAME $BASE_DIR